name: Microservice docker image build

on:
  workflow_call:
    inputs:
      disable-unit-tests:
        required: false
        default: false
        type: boolean
      enable-code-scans:
        required: false
        type: boolean
      enable-image-signing:
        required: false
        type: boolean
      k8s-microservice-name:
        required: false
        type: string
      k8s-namespace:
        required: false
        type: string
      should-deploy:
        required: false
        type: boolean
        default: true
    secrets:
      ghcr-token:
        required: true
        description: Github token allowing access to the libraries and ghcr.
      drone-server:
        required: false
        description: Drone server url.
      drone-token:
        required: false
        description: Drone token.
      signing-key:
        required: false
        description: Image signing key
      signing-password:
        required: false
        description: Image signing password

env:
  GOPRIVATE: "github.com/telegram-bot-app/*"
  ENABLE_CODE_SCANS: ${{ inputs.enable-code-scans }}
  ENABLE_IMAGE_SIGNING: ${{ inputs.enable-image-signing }}
  SHOULD_DEPLOY: "${{ inputs.should-deploy }}"
  GO_VERSION: "1.22.6"

jobs:
  prepare-and-test:
    name: Prepare and Test
    runs-on: tgbotapp-runner
    container:
      image: ghcr.io/actions/actions-runner:latest
    # services:
    #   redis:
    #     image: redis:7.4.0-alpine
    #     options: >-
    #       --health-cmd "redis-cli ping"
    #       --health-interval 10s
    #       --health-timeout 5s
    #       --health-retries 5
    outputs:
      SANITISED_REPOSITORY_NAME: ${{ steps.get_env.outputs.SANITISED_REPOSITORY_NAME }}
      DOCKER_IMAGE: ${{ steps.get_env.outputs.DOCKER_IMAGE }}
      GITHUB_COMMIT_NUMBER: ${{ steps.get_env.outputs.GITHUB_COMMIT_NUMBER }}
      GITHUB_SHA: ${{ steps.get_env.outputs.GITHUB_SHA }}
      DOCKER_IMAGE_SEMVER: ${{ steps.semver.outputs.semantic_version }}
    steps:
      - name: Install dependencies
        uses: nick-invision/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: sudo apt-get -qq install git make -y

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set environment variables
        id: get_env
        run: |
          TMP_SANITISED_REPOSITORY_NAME=$(echo ${{ github.event.repository.name }} | sed -e 's|\.|-|g')
          echo "SANITISED_REPOSITORY_NAME=$TMP_SANITISED_REPOSITORY_NAME" >> $GITHUB_OUTPUT
          echo "DOCKER_IMAGE=ghcr.io/${{ github.repository_owner }}/$TMP_SANITISED_REPOSITORY_NAME" >> $GITHUB_OUTPUT

      - name: Establish semver
        id: semver
        uses: lukaszraczylo/semver-generator@v1
        env:
          SEMVER_RAW_FLAGS: "--debug"
        with:
          config_file: semver.yaml
          repository_local: true
          github_username: ${{ github.ACTOR }}
          github_token: ${{ secrets.ghcr-token }}

      - name: Install Go
        uses: actions/setup-go@v5
        id: cache
        with:
          cache: true
          check-latest: false
          go-version: ${{env.GO_VERSION}}
          cache-dependency-path: "**/*.sum"

      - name: Configure git for private modules
        uses: extractions/netrc@v2
        with:
          machine: github.com
          username: ${{ github.actor }}
          password: ${{ secrets.ghcr-token }}

      - name: Get dependencies and run tests
        run: |
          go get ./...
          if [ -f ./addons.sh ]; then
            ./addons.sh
          fi
          if [ "${{ inputs.disable-unit-tests }}" != "true" ]; then
            export REDIS_SERVER="redis:6379"
            CI_RUN=${CI} make test
          fi

      - name: Run code scans
        if: env.ENABLE_CODE_SCANS == true
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          gosec ./...

  build-and-push:
    needs: prepare-and-test
    name: Build and Push Docker Image
    runs-on: tgbotapp-runner
    container:
      image: quay.io/buildah/stable:latest
    steps:
      - name: Install dependencies
        uses: nick-invision/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: sudo dnf install -y git make qemu-user-static

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure git for private modules
        uses: extractions/netrc@v2
        with:
          machine: github.com
          username: ${{ github.actor }}
          password: ${{ secrets.ghcr-token }}

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.ACTOR }}
          password: ${{ secrets.ghcr-token }}

      - name: Install Go
        uses: actions/setup-go@v5
        id: cache
        with:
          cache: true
          check-latest: false
          go-version: ${{env.GO_VERSION}}
          cache-dependency-path: "**/*.sum"

      - name: Conditional dependencies
        run: |
          if [ -f ./addons.sh ]; then
            ./addons.sh
          fi

      - name: Build binaries
        run: |
          export LOCAL_VERSION=${{ needs.prepare-and-test.outputs.DOCKER_IMAGE_SEMVER }}
          export SANITISED_REPOSITORY_NAME=${{ needs.prepare-and-test.outputs.SANITISED_REPOSITORY_NAME }}
          export GOLDFLAGS="-s -w -X github.com/telegram-bot-app/libpack/config.PKG_NAME=$SANITISED_REPOSITORY_NAME -X github.com/telegram-bot-app/libpack/config.PKG_VERSION=$LOCAL_VERSION -X main.PKG_VERSION=$LOCAL_VERSION -X main.SVC_NAME=$SANITISED_REPOSITORY_NAME -X main.SVC_VERSION=`$(date +\"%Y%m%d%H%M\")`"

          # if $SANITISED_REPOSITORY_NAME is "ms-text-analysis" then use CGO_ENABLED=1
          # else use CGO_ENABLED=0
          if [ "$SANITISED_REPOSITORY_NAME" = "ms-text-analysis" ]; then
            export CGO_ENABLED=1
          else
            export CGO_ENABLED=0
          fi

          GOOS=linux GOARCH=amd64 go build -a -ldflags="$GOLDFLAGS" -o dist/bot-linux-amd64
          GOOS=linux GOARCH=arm64 go build -a -ldflags="$GOLDFLAGS" -o dist/bot-linux-arm64
          chmod -R 777 dist/*

      - name: Build Image
        uses: redhat-actions/buildah-build@v2
        with:
          archs: amd64,arm64
          # platforms: linux/amd64,linux/arm64
          image: ${{ needs.prepare-and-test.outputs.DOCKER_IMAGE }}
          tags: ${{ github.sha }} ${{ needs.prepare-and-test.outputs.DOCKER_IMAGE_SEMVER }} latest
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ github.event.repository.updated_at }}
            org.opencontainers.image.version=${{ needs.prepare-and-test.outputs.DOCKER_IMAGE_SEMVER }}
            com.github.repo.branch=${{ github.ref_name }}
          context: .
          containerfiles: Dockerfile
          # build-args: |
          #   GITHUB_SHA=${{ github.sha }}
          #   GITHUB_COMMIT_NUMBER=${{ needs.prepare-and-test.outputs.GITHUB_COMMIT_NUMBER }}

      # - name: Build and push
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: .
      #     platforms: linux/amd64,linux/arm64
      #     push: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' }}
      #     tags: |
      #       ${{ needs.prepare-and-test.outputs.DOCKER_IMAGE }}:${{ github.sha }}
      #       ${{ needs.prepare-and-test.outputs.DOCKER_IMAGE }}:${{ needs.prepare-and-test.outputs.DOCKER_IMAGE_SEMVER }}
      #       ${{ needs.prepare-and-test.outputs.DOCKER_IMAGE }}:latest
      #     labels: |
      #       org.opencontainers.image.revision=${{ github.sha }}
      #       org.opencontainers.image.created=${{ github.event.repository.updated_at }}
      #       org.opencontainers.image.version=${{ needs.prepare-and-test.outputs.DOCKER_IMAGE_SEMVER }}
      #       com.github.repo.branch=${{ github.ref_name }}
      #     cache-from: type=gha
      #     cache-to: type=gha,mode=max

  release-and-deploy:
    needs: [prepare-and-test, build-and-push]
    name: Release and Deploy
    runs-on: tgbotapp-runner
    container:
      image: ghcr.io/actions/actions-runner:latest
    steps:
      - name: Install dependencies
        uses: nick-invision/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: |
            woodpecker_cached_client=/home/runner/.cache/woodpecker.tar.gz
            sudo apt-get install git -y
            # if the woodpecker-cli is not cached, download it
            if [ ! -f $woodpecker_cached_client ]; then
              sudo apt-get install curl -y
              curl -sL https://github.com/woodpecker-ci/woodpecker/releases/download/v2.7.0/woodpecker-cli_linux_arm64.tar.gz -o $woodpecker_cached_client
              tar -xvf $woodpecker_cached_client -C /home/runner/.cache/
            fi
            sudo cp /home/runner/.cache/woodpecker-cli /usr/local/bin/woodpecker-cli

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: v${{ needs.prepare-and-test.outputs.DOCKER_IMAGE_SEMVER }}
          body: ${{ github.event.head_commit.message }}
          token: ${{ secrets.ghcr-token }}
          tag_name: v${{ needs.prepare-and-test.outputs.DOCKER_IMAGE_SEMVER }}
          prerelease: ${{ github.ref != 'refs/heads/master' && github.ref != 'refs/heads/main' }}

      - name: Deploy to dev cluster
        if: inputs.should-deploy == true
        env:
          DRONE_SERVER: ${{ secrets.drone-server }}
          DRONE_TOKEN: ${{ secrets.drone-token }}
        shell: bash -l {0}
        run: |
          woodpecker-cli setup --server ${{ secrets.drone-server }} --token ${{ secrets.drone-token }}
          woodpecker-cli deploy ${{ github.repository }} \
            --param IMAGE_VERSION=${{ needs.prepare-and-test.outputs.DOCKER_IMAGE }}:${{ needs.prepare-and-test.outputs.DOCKER_IMAGE_SEMVER }} --param IMAGE_NAMESPACE=${{ inputs.k8s-namespace }} --param IMAGE_DEPLOYMENT_NAME=${{ inputs.k8s-microservice-name }}
