name: Microservice docker image build

on:
  workflow_call:
    inputs:
      disable-unit-tests:
        required: false
        default: false
        type: boolean
      enable-code-scans:
        required: false
        type: boolean
      enable-image-signing:
        required: false
        type: boolean
      k8s-microservice-name:
        required: false
        type: string
      k8s-namespace:
        required: false
        type: string
      should-deploy:
        required: false
        type: boolean
        default: true
    secrets:
      ghcr-token:
        required: true
        description: Github token allowing access to the libraries and ghcr.
      drone-server:
        required: false
        description: Drone server url.
      drone-token:
        required: false
        description: Drone token.
      signing-key:
        required: false
        description: Image signing key
      signing-password:
        required: false
        description: Image signing password

env:
  GOPRIVATE: "github.com/telegram-bot-app/*"
  ENABLE_CODE_SCANS: ${{ inputs.enable-code-scans }}
  ENABLE_IMAGE_SIGNING: ${{ inputs.enable-image-signing }}
  SHOULD_DEPLOY: "${{ inputs.should-deploy }}"
  GO_VERSION: "1.22"

jobs:
  prepare-and-test:
    name: Prepare and Test
    runs-on: tgbotapp-runner
    # container:
    #   image: golang:1.22
    env:
      GOHOME: /home/runner/go
    # services:
    #   redis:
    #     image: redis:7.4.0-alpine
    #     options: >-
    #       --health-cmd "redis-cli ping"
    #       --health-interval 10s
    #       --health-timeout 5s
    #       --health-retries 5
    outputs:
      SANITISED_REPOSITORY_NAME: ${{ steps.get_env.outputs.SANITISED_REPOSITORY_NAME }}
      DOCKER_IMAGE: ${{ steps.get_env.outputs.DOCKER_IMAGE }}
      GITHUB_COMMIT_NUMBER: ${{ steps.get_env.outputs.GITHUB_COMMIT_NUMBER }}
      GITHUB_SHA: ${{ steps.get_env.outputs.GITHUB_SHA }}
      DOCKER_IMAGE_SEMVER: ${{ steps.semver.outputs.semantic_version }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set environment variables
        id: get_env
        run: |
          TMP_SANITISED_REPOSITORY_NAME=$(echo ${{ github.event.repository.name }} | sed -e 's|\.|-|g')
          echo "SANITISED_REPOSITORY_NAME=$TMP_SANITISED_REPOSITORY_NAME" >> $GITHUB_OUTPUT
          echo "DOCKER_IMAGE=ghcr.io/${{ github.repository_owner }}/$TMP_SANITISED_REPOSITORY_NAME" >> $GITHUB_OUTPUT

      - name: Establish semver
        id: semver
        uses: lukaszraczylo/semver-generator@v1
        env:
          SEMVER_RAW_FLAGS: "--debug"
        with:
          config_file: semver.yaml
          repository_local: true
          github_username: ${{ github.ACTOR }}
          github_token: ${{ secrets.ghcr-token }}

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Configure git for private modules
        uses: extractions/netrc@v2
        with:
          machine: github.com
          username: ${{ github.actor }}
          password: ${{ secrets.ghcr-token }}

      - name: Get dependencies and run tests
        run: |
          go get ./...
          if [ -f ./addons.sh ]; then
            ./addons.sh
          fi
          if [ "${{ inputs.disable-unit-tests }}" != "true" ]; then
            export REDIS_SERVER="redis:6379"
            CI_RUN=${CI} make test
          fi

      - name: Run code scans
        if: env.ENABLE_CODE_SCANS == true
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          gosec ./...

  build-and-push:
    needs: prepare-and-test
    name: Build and Push Docker Image
    runs-on: tgbotapp-runner
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure git for private modules
        uses: extractions/netrc@v2
        with:
          machine: github.com
          username: ${{ github.actor }}
          password: ${{ secrets.ghcr-token }}

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Conditional dependencies
        run: |
          go get ./...
          if [ -f ./addons.sh ]; then
            ./addons.sh
          fi

      - name: Build binaries
        run: |
          export LOCAL_VERSION=${{ needs.prepare-and-test.outputs.DOCKER_IMAGE_SEMVER }}
          export SANITISED_REPOSITORY_NAME=${{ needs.prepare-and-test.outputs.SANITISED_REPOSITORY_NAME }}
          export GOLDFLAGS="-s -w -X github.com/telegram-bot-app/libpack/config.PKG_NAME=$SANITISED_REPOSITORY_NAME -X github.com/telegram-bot-app/libpack/config.PKG_VERSION=$LOCAL_VERSION -X main.PKG_VERSION=$LOCAL_VERSION -X main.SVC_NAME=$SANITISED_REPOSITORY_NAME -X main.SVC_VERSION=`$(date +\"%Y%m%d%H%M\")`"

          # if $SANITISED_REPOSITORY_NAME is "ms-text-analysis" then use CGO_ENABLED=1
          # else use CGO_ENABLED=0
          if [ "$SANITISED_REPOSITORY_NAME" = "ms-text-analysis" ]; then
            export CGO_ENABLED=1
          else
            export CGO_ENABLED=0
          fi

          GOOS=linux GOARCH=amd64 go build -a -ldflags="$GOLDFLAGS" -o dist/bot-linux-amd64
          GOOS=linux GOARCH=arm64 go build -a -ldflags="$GOLDFLAGS" -o dist/bot-linux-arm64
          chmod -R 777 dist/*

      - name: Build Image
        uses: redhat-actions/buildah-build@v2
        with:
          archs: amd64,arm64
          # platforms: linux/amd64,linux/arm64
          image: ${{ needs.prepare-and-test.outputs.DOCKER_IMAGE }}
          tags: ${{ github.sha }} ${{ needs.prepare-and-test.outputs.DOCKER_IMAGE_SEMVER }} latest
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ github.event.repository.updated_at }}
            org.opencontainers.image.version=${{ needs.prepare-and-test.outputs.DOCKER_IMAGE_SEMVER }}
            com.github.repo.branch=${{ github.ref_name }}
          context: .
          containerfiles: Dockerfile

      - name: Push to ghcr
        id: push-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' }}
        with:
          image: ${{ needs.prepare-and-test.outputs.DOCKER_IMAGE }}
          tags: ${{ github.sha }} ${{ needs.prepare-and-test.outputs.DOCKER_IMAGE_SEMVER }} latest
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ghcr-token }}

  release-and-deploy:
    needs: [prepare-and-test, build-and-push]
    name: Release and Deploy
    runs-on: tgbotapp-runner
    steps:
      # - name: Create Release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     name: v${{ needs.prepare-and-test.outputs.DOCKER_IMAGE_SEMVER }}
      #     body: ${{ github.event.head_commit.message }}
      #     token: ${{ secrets.ghcr-token }}
      #     tag_name: v${{ needs.prepare-and-test.outputs.DOCKER_IMAGE_SEMVER }}
      #     prerelease: ${{ github.ref != 'refs/heads/master' && github.ref != 'refs/heads/main' }}

      - name: Deploy to dev cluster
        if: inputs.should-deploy == true
        env:
          DRONE_SERVER: ${{ secrets.drone-server }}
          DRONE_TOKEN: ${{ secrets.drone-token }}
        run: |
          kubectl set image deployment/${{ inputs.k8s-microservice-name }} microservice=${{ needs.prepare-and-test.outputs.DOCKER_IMAGE }}:${{ needs.prepare-and-test.outputs.DOCKER_IMAGE_SEMVER }} -n ${{ inputs.k8s-namespace }}

          # woodpecker-cli setup --server ${{ secrets.drone-server }} --token ${{ secrets.drone-token }}
          # woodpecker-cli deploy ${{ github.repository }} \
          #   --param IMAGE_VERSION=${{ needs.prepare-and-test.outputs.DOCKER_IMAGE }}:${{ needs.prepare-and-test.outputs.DOCKER_IMAGE_SEMVER }} --param IMAGE_NAMESPACE=${{ inputs.k8s-namespace }} --param IMAGE_DEPLOYMENT_NAME=${{ inputs.k8s-microservice-name }}
